<?php
	for($i = 0; $i < sizeof($accounts); $i++) {
		$accounts[$i]['total'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "'"))['ct'];
		$accounts[$i]['open'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND status = 'Open'"))['ct'];
		$accounts[$i]['inpr'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND status = 'In Progress'"))['ct'];
		$accounts[$i]['comp'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND status = 'Completed'"))['ct'];
		$accounts[$i]['canc'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND status = 'Cancelled'"))['ct'];
		$accounts[$i]['fail'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND status = 'Failed'"))['ct'];
		$accounts[$i]['week'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND WEEK(pht_start_datetime, 1) = WEEK(NOW(), 1) AND YEAR(pht_start_datetime) = YEAR(NOW())"))['ct'];
		$accounts[$i]['mont'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND MONTH(pht_start_datetime) = MONTH(NOW()) AND YEAR(pht_start_datetime) = YEAR(NOW())"))['ct'];
		$accounts[$i]['norm'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND change_type LIKE 'Normal%'"))['ct'];
		$accounts[$i]['stnd'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND change_type = 'Standard'"))['ct'];
		$accounts[$i]['tran'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND actions = 'Import Transport'"))['ct'];
		$accounts[$i]['emer'] = mysqli_fetch_assoc(mysqli_query($ch_conn, "SELECT COUNT(i.item_id) as ct FROM items i, account a WHERE i.account_id = a.acct_id AND a.team_id IN (" . implode(', ', $managed_teams_ids) . ") AND a.acct_abbrev = '" . $accounts[$i]['acct_abbrev'] . "' AND change_type = 'Emergency'"))['ct'];
	}
?>